### ISSUE TITLE
Syft panics when processing SIF from 'registry' source

### ISSUE THREAD

**Issue by tri-adam** [anchore/syft#1242]
**What happened**:

When running `syft packages` against a `registry:` source that contains a SIF image, a `panic` occurs:

```sh
$ syft packages registry:core.harbor.domain/library/alpine:latest
panic: runtime error: index out of range [0] with length 0

goroutine 91 [running]:
github.com/anchore/stereoscope/pkg/image.newLayerMetadata({{0xc00056c730, 0x47}, 0x0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {{0x0, ...}}, ...}, ...}, ...)
        /Users/runner/go/pkg/mod/github.com/anchore/stereoscope@v0.0.0-20220921141924-56552770e555/pkg/image/layer_metadata.go:26 +0x1dd
github.com/anchore/stereoscope/pkg/image.(*Layer).Read(_, _, {{0xc00056c730, 0x47}, 0x0, {{0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
        /Users/runner/go/pkg/mod/github.com/anchore/stereoscope@v0.0.0-20220921141924-56552770e555/pkg/image/layer.go:85 +0xc8
github.com/anchore/stereoscope/pkg/image.(*Image).Read(0xc000544380)
        /Users/runner/go/pkg/mod/github.com/anchore/stereoscope@v0.0.0-20220921141924-56552770e555/pkg/image/image.go:204 +0x4ed
github.com/anchore/stereoscope.GetImageFromSource({0x28bda40, 0xc0000500a0}, {0x7fffc6400386, 0x28}, 0x5, {0xc0001fe030, 0x1, 0x0?})
        /Users/runner/go/pkg/mod/github.com/anchore/stereoscope@v0.0.0-20220921141924-56552770e555/client.go:92 +0x2d5
github.com/anchore/syft/syft/source.getImageWithRetryStrategy({{0x7fffc640037d, 0x31}, {0x24ad5cd, 0xb}, 0x5, {0x7fffc6400386, 0x28}, {0x0, 0x0}, 0x1}, ...)
        /Users/runner/work/syft/syft/syft/source/source.go:160 +0x29f
github.com/anchore/syft/syft/source.generateImageSource({{0x7fffc640037d, 0x31}, {0x24ad5cd, 0xb}, 0x5, {0x7fffc6400386, 0x28}, {0x0, 0x0}, 0x1}, ...)
        /Users/runner/work/syft/syft/syft/source/source.go:126 +0x58
github.com/anchore/syft/syft/source.New({{0x7fffc640037d, 0x31}, {0x24ad5cd, 0xb}, 0x5, {0x7fffc6400386, 0x28}, {0x0, 0x0}, 0x1}, ...)
        /Users/runner/work/syft/syft/syft/source/source.go:113 +0xf8
github.com/anchore/syft/cmd/syft/cli/packages.execWorker.func1()
        /Users/runner/work/syft/syft/cmd/syft/cli/packages/packages.go:72 +0x1e5
created by github.com/anchore/syft/cmd/syft/cli/packages.execWorker
        /Users/runner/work/syft/syft/cmd/syft/cli/packages/packages.go:69 +0x125
```

**What you expected to happen**:

Expected the same output as running `syft packages` against the SIF image locally:

```sh
$ singularity pull image.sif oras://core.harbor.domain/library/alpine:latest
INFO:    Downloading oras image
$ syft packages image.sif 
 ✔ Parsed image            
 ✔ Cataloged packages      [14 packages]
NAME                    VERSION      TYPE 
alpine-baselayout       3.2.0-r22    apk   
alpine-baselayout-data  3.2.0-r22    apk   
alpine-keys             2.4-r1       apk   
apk-tools               2.12.9-r3    apk   
busybox                 1.35.0-r17   apk   
ca-certificates-bundle  20220614-r0  apk   
libc-utils              0.7.2-r3     apk   
libcrypto1.1            1.1.1q-r0    apk   
libssl1.1               1.1.1q-r0    apk   
musl                    1.2.3-r0     apk   
musl-utils              1.2.3-r0     apk   
scanelf                 1.3.4-r0     apk   
ssl_client              1.35.0-r17   apk   
zlib                    1.2.12-r3    apk
```

**How to reproduce it (as minimally and precisely as possible)**:

Using [SingularityCE](https://github.com/sylabs/singularity), push a SIF image to a supported OCI registry (I used [Harbor](https://goharbor.io)), and process with Syft:

```sh
singularity pull docker://alpine
singularity push alpine_latest.sif oras://core.harbor.domain/library/alpine:latest
syft packages registry:core.harbor.domain/library/alpine:latest
```

**Anything else we need to know?**:

**Environment**:

```sh
$ syft version
Application:        syft
Version:            0.58.0
JsonSchemaVersion:  4.0.0
BuildDate:          2022-09-29T19:59:22Z
GitCommit:          b9b13d5525df89194d332467f692bc28bc68d07f
GitDescription:     v0.58.0
Platform:           linux/amd64
GoVersion:          go1.18.6
Compiler:           gc
```

```sh
$ singularity --version
singularity-ce version 3.10.2
```

```sh
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by kzantow** [comment]
Hey, @tri-adam -- sorry for the delay here. We had a look at this. Do you happen to have a working example of this issue with a public repository we could look at? We'd definitely like to get any panics fixed if this is still happening.

Additionally, I created this issue to add support for ORAS: https://github.com/anchore/stereoscope/issues/253
