### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by talleno** [anchore/syft#1559]
**Please provide a set of steps on how to reproduce the issue**

**What happened**:
Hello,
When i launch syft with the following command line i have got an error.
```
[~]$ ./syft -q packages dir:/ --exclude ./dev --exclude ./proc --exclude ./sys --exclude ./usr/share --exclude ./var/lib/containers --exclude ./var/lib/docker -o json=/tmp/syft.json
 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc22017]

goroutine 14 [running]:
github.com/anchore/syft/syft/source.directoryResolver.FilesByPath({{0x7ffedebca49d, 0x1}, {0x0, 0x0}, {0xc000a3699b, 0x5}, {0xc000a369a0, 0x10}, 0xc000012180, 0xc000a66a50, ...}, ...)
	/home/runner/work/syft/syft/syft/source/directory_resolver.go:378 +0x297
github.com/anchore/syft/syft/pkg/cataloger.packageFileOwnershipRelationships({{0xc001f08b00, 0x10}, {0xc000f18730, 0x6}, {0xc00247cdf0, 0xb}, {0x12bbe07, 0x10}, {0xc001dd7920}, {0xc0009a3e00, ...}, ...}, ...)
	/home/runner/work/syft/syft/syft/pkg/cataloger/catalog.go:190 +0x1a6
github.com/anchore/syft/syft/pkg/cataloger.runCataloger({0x14b60c8, 0xc001c438f0}, {0x14bf5d8?, 0xc0001fc180})
	/home/runner/work/syft/syft/syft/pkg/cataloger/catalog.go:81 +0x885
github.com/anchore/syft/syft/pkg/cataloger.Catalog.func1()
	/home/runner/work/syft/syft/syft/pkg/cataloger/catalog.go:127 +0x105
created by github.com/anchore/syft/syft/pkg/cataloger.Catalog
	/home/runner/work/syft/syft/syft/pkg/cataloger/catalog.go:122 +0x2b0
```

**What you expected to happen**:

**Anything else we need to know?**:

It's work fine with the version 0.68.1 but i have got the same error with versions 0.69.0, 0.69.1 and 0.70.0. The bug occur on rocky or ubuntu servers.

**Environment**:
- Output of `syft version`: 
```
[~]$ ./syft --version
syft 0.70.0
```
- OS (e.g: `cat /etc/os-release` or similar):
```
cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by kzantow** [comment]
Thanks for the report @talleno -- I think I see the issue, it should be a quick fix

**Comment by kzantow** [comment]
@talleno do you happen to have an image you could point to that could reproduce this issue? running locally with `docker run -it ubuntu:latest` doesn't seem to exhibit the issue

**Comment by talleno** [comment]
@kzantow for the moment i only test on virtual machines.

**Comment by talleno** [comment]
Hi @kzantow 
I relaunch test with the new version 0.71.0 and the bug is fixed. 
The issue can be closed.

**Comment by kzantow** [comment]
Great, thanks for following up @talleno !
