### ISSUE TITLE
issue with connecting to https://jeremylong.github.io/DependencyCheck/current.txt

### ISSUE THREAD

**Issue by Mujkauser** [anchore/syft#1942]
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.305 s <<< FAILURE! -- in org.owasp.dependencycheck.utils.HttpResourceConnectionTest
[ERROR] org.owasp.dependencycheck.utils.HttpResourceConnectionTest.testFetch -- Time elapsed: 0.300 s <<< ERROR!
org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://jeremylong.github.io/DependencyCheck/current.txt; unable to connect.
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:267)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:163)
        at org.owasp.dependencycheck.utils.HttpResourceConnectionTest.testFetch(HttpResourceConnectionTest.java:41)
Caused by: java.net.UnknownHostException: jeremylong.github.io
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:206)
        ... 2 more

[ERROR] org.owasp.dependencycheck.utils.HttpResourceConnectionTest.testIsClosed -- Time elapsed: 0.001 s <<< ERROR!
org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://jeremylong.github.io/DependencyCheck/current.txt; unable to connect.
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:267)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.fetch(HttpResourceConnection.java:163)
        at org.owasp.dependencycheck.utils.HttpResourceConnectionTest.testIsClosed(HttpResourceConnectionTest.java:69)
Caused by: java.net.UnknownHostException: jeremylong.github.io
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at org.owasp.dependencycheck.utils.HttpResourceConnection.obtainConnection(HttpResourceConnection.java:206)
        ... 2 more

[INFO] Running org.owasp.dependencycheck.utils.JsonArrayFixingInputStreamTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 s -- in org.owasp.dependencycheck.utils.JsonArrayFixingInputStreamTest
[INFO] Running org.owasp.dependencycheck.utils.search.FileContentSearchTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s -- in org.owasp.dependencycheck.utils.search.FileContentSearchTest
[INFO] Running org.owasp.dependencycheck.utils.SettingsTest
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.035 s -- in org.owasp.dependencycheck.utils.SettingsTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   HttpResourceConnectionTest.testFetch:41 ▒ DownloadFailed Error downloading file https://jeremylong.github.io/DependencyCheck/current.txt; unable to connect.
[ERROR]   HttpResourceConnectionTest.testIsClosed:69 ▒ DownloadFailed Error downloading file https://jeremylong.github.io/DependencyCheck/current.txt; unable to connect.
[INFO]
[ERROR] Tests run: 51, Failures: 0, Errors: 2, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Dependency-Check 8.3.2-SNAPSHOT:
[INFO]
[INFO] Dependency-Check ................................... SUCCESS [  4.717 s]
[INFO] Dependency-Check Utils ............................. FAILURE [ 11.822 s]
[INFO] Dependency-Check Core .............................. SKIPPED
[INFO] Dependency-Check Command Line ...................... SKIPPED
[INFO] Dependency-Check Ant Task .......................... SKIPPED
[INFO] Dependency-Check Maven Plugin ...................... SKIPPED
[INFO] Dependency-Check Plugin Archetype .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.881 s
[INFO] Finished at: 2023-07-14T10:38:28+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project dependency-check-utils:
[ERROR]
[ERROR] Please refer to D:\DependencyCheck\utils\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dependency-check-utils

**Comment by tgerla** [comment]
Hi @Mujkauser, this looks like maybe a temporary GitHub outage. Can you try again? Also, I don't recognize this log output. It doesn't look like a Syft build. Can you share more details about what you are doing, and we can try to help?

**Comment by tgerla** [comment]
We'll close this issue but let us know if you have further problems.
