### ISSUE TITLE
Syft cli.Command() panics when invoked multiple times

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#2285]
**What happened**:
See https://stackoverflow.com/questions/77387892/unable-to-call-anchore-syft-library-command-multiple-times-when-embedded-in-go-a

```golang
func generateCycloneDX(ociArchiveName string, jsonOutputName string) {
    syftId := clio.Identification{Name: "syft"}
    syftCommand := cli.Command(syftId)
    syftCommand.SetArgs([]string{ociArchiveName, "-o", jsonOutputName})
    err := syftCommand.Execute()
    if err != nil {
        panic(err)
    }
}
```

Which results in:
```
panic: replace existing redaction store (probably unintentional)

goroutine 1 [running]:
github.com/anchore/syft/internal/redact.Set(...)
        go/pkg/mod/github.com/anchore/syft@v0.93.0/internal/redact/redact.go:11
github.com/anchore/syft/cmd/syft/cli.create.func2(0xc000490a90?)
        go/pkg/mod/github.com/anchore/syft@v0.93.0/cmd/syft/cli/cli.go:64 +0x1a5
github.com/anchore/clio.(*application).runInitializers(0xc0013bc1a0)
        go/pkg/mod/github.com/anchore/clio@v0.0.0-20231016125707-b60d41410795/application.go:110 +0x66
github.com/anchore/clio.(*application).PostLoad(0xc0013bc1a0)
        go/pkg/mod/github.com/anchore/clio@v0.0.0-20231016125707-b60d41410795/application.go:105 +0xbb
github.com/anchore/fangs.postLoad({0x1f81f40?, 0xc0013bc1a0?, 0xc0013bc1a0?})
        go/pkg/mod/github.com/anchore/fangs@v0.0.0-20230818131516-2186b10924fe/load.go:201 +0x1e5
github.com/anchore/fangs.loadConfig({{0x26109f8, 0x349e4e0}, {0x1ff3df6, 0x4}, {0x2004cda, 0xc}, {0x0, 0x0}, {0xc002b25e30, 0x5, ...}}, ...)
        go/pkg/mod/github.com/anchore/fangs@v0.0.0-20230818131516-2186b10924fe/load.go:80 +0x7d1
github.com/anchore/fangs.Load({{0x26109f8, 0x349e4e0}, {0x1ff3df6, 0x4}, {0x2004cda, 0xc}, {0x0, 0x0}, {0xc002b25e30, 0x5, ...}}, ...)
        go/pkg/mod/github.com/anchore/fangs@v0.0.0-20230818131516-2186b10924fe/load.go:16 +0x74
github.com/anchore/clio.(*application).loadConfigs(0xc0013bc1a0, 0xc000033870?, {0xc0004909f0, 0x1, 0xc0013b2700?})
        go/pkg/mod/github.com/anchore/clio@v0.0.0-20231016125707-b60d41410795/application.go:95 +0x1a5
github.com/anchore/clio.(*application).setupCommand.func1.(*application).Setup.func1(0x4?, {0xd631f2?, 0xc0013b2700?, 0xc000033af0?})
        go/pkg/mod/github.com/anchore/clio@v0.0.0-20231016125707-b60d41410795/application.go:74 +0x45
github.com/anchore/clio.(*application).setupCommand.func1(0xc0013b2700?, {0xc002e20870, 0x1, 0x3})
        go/pkg/mod/github.com/anchore/clio@v0.0.0-20231016125707-b60d41410795/application.go:316 +0x82
github.com/spf13/cobra.(*Command).execute(0xc000845200, {0xc002e20660, 0x3, 0x3})
        go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:925 +0x7f6
github.com/spf13/cobra.(*Command).ExecuteC(0xc000845200)
        go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
```

**What you expected to happen**:
The panic is well intentioned, however, it is unintentional that it this panics on the second invocation.

**Comment by arbelonson-source** [comment]
Traced this — happy to open a PR if you're okay with it. Disclosure up front: I run agent loops (Claude Code) that find and fix issues like this, so this diagnosis and fix are AI-produced, not something I personally read the code for. Asking before opening a PR rather than doing it unprompted.

**Root cause**: `internal/redact/redact.go`'s `Set` panics whenever a store is already present:

```go
func Set(s redact.Store) {
	if store != nil {
		panic("replace existing redaction store (probably unintentional)")
	}
	store = s
}
```

It's called once per `clio.Application`/`cli.Command()` construction, in `cmd/syft/internal/clio_setup_config.go`'s `WithInitializers`, right alongside `bus.Set(state.Bus)` and `log.Set(state.Logger)` — neither of which panics on replacement, they just overwrite. Calling `cli.Command()` more than once in the same process (as this issue's linked repro does) hits the panic on the second call, well after the first invocation's `Execute()` has already returned and its store is no longer needed for anything.

**Fix**: make `redact.Set` match its two siblings — overwrite unconditionally, no panic.

**Verified end-to-end**, not just at the unit level: a small Go program calling `cli.Command(id)`, `SetArgs`, `Execute()` twice in the same process reproduces the exact panic and stack trace from this issue on current `main` (`redact.Set` → `AppClioSetupConfig`'s initializer → `runInitializers` → `PostLoad` → `loadConfigs`), and completes both calls cleanly with the fix applied. Also added a unit test in `internal/redact` and confirmed it fails on `main` and passes with the fix; `go build ./...`, `go vet`, and the existing `internal/redact` + `cmd/syft/internal/commands` test suites all pass.

Diff, if useful before a PR exists: https://github.com/anchore/syft/compare/main...arbelonson-source:syft:fix/2285-redact-set-double-invocation-panic
