### ISSUE TITLE
v0.104.0 interface conversion error when creating bom from singularity image

### ISSUE THREAD

**Issue by wresch** [anchore/syft#2628]
**What happened**:

```console
$ syft --version
syft 0.104.0
$ singularity pull docker://alpine:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
INFO:    Fetching OCI image...
3.3MiB / 3.3MiB [=========================] 100 %0s
INFO:    Extracting OCI image...
INFO:    Inserting Singularity configuration...
INFO:    Creating SIF file...
$ syft singularity:alpine_latest.sif -o cyclonedx-json=alpine_latest.sbom.cdx.json
 ✔ Parsed image                                                               sha256:3fecde77bf724eebcbc616d40b6ee91eba063d3fdc0411372c35d59653426ea8
 ⠴ Cataloging contents             ━━━━━━━━━━━━━━━━━━━━                              0c2bd17c0f97377377723af90ac9106933bd250c40ccb9b307cc1dbe0005a54d
   ├── ⠴ Packages                        [16 packages]
   ├── ✔ File digests                    [80 files]
   ├── ✔ File metadata                   [80 locations]
   └── ⠹ Executables                     ━━━━━━━━━━━━━━━━━━━━  [/bin/busybox]
failed to run tasks: 1 error occurred:
        * failed to run task: interface conversion: *squashfs.File is not unionreader.UnionReader: missing method ReadAt at:
goroutine 527 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/anchore/syft/internal/task.runTaskSafely.func1()
        /home/runner/work/syft/syft/internal/task/executor.go:67 +0x3d
panic({0x168c160?, 0xc000fc3ec0?})
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/panic.go:914 +0x21f
github.com/anchore/syft/syft/file/cataloger/executable.(*Cataloger).Catalog(0xc0004d48d0, {0x1e805b0, 0xc0000d6970})
        /home/runner/work/syft/syft/syft/file/cataloger/executable/cataloger.go:69 +0x3d0
github.com/anchore/syft/internal/task.NewExecutableCatalogerTask.func1({0x1e78a00?, 0xc000ea7eb0?}, {0x1e805b0, 0xc0000d6970}, {0x1e76140?, 0xc000401100})
        /home/runner/work/syft/syft/internal/task/file_tasks.go:114 +0x57
github.com/anchore/syft/internal/task.task.Execute(...)
        /home/runner/work/syft/syft/internal/task/task.go:64
github.com/anchore/syft/internal/task.runTaskSafely({0x1e78a00?, 0xc0008cc910?}, {0x1e71940?, 0xc0002a3380?}, {0x1e805b0?, 0xc0000d6970?}, {0x1e76140?, 0xc000401100?})
        /home/runner/work/syft/syft/internal/task/executor.go:71 +0xa7
github.com/anchore/syft/internal/task.(*Executor).Execute.func1()
        /home/runner/work/syft/syft/internal/task/executor.go:49 +0x131
created by github.com/anchore/syft/internal/task.(*Executor).Execute in goroutine 31
        /home/runner/work/syft/syft/internal/task/executor.go:40 +0x8a


$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

```

- This is not image specific - i tried a couple of others with  the same result
- version 0.103.1 runs successfully on the same image

**Comment by wresch** [comment]
Thanks!
