### ISSUE TITLE
Segmentation Fault when running Syft in Docker containers

### ISSUE THREAD

**Issue by rosswilhite-wk** [anchore/syft#638]
**What happened**:
We are trying to write unit tests for Syft in our CI/CD service. When installing syft in a dockerfile, we are unable to actually run the service within a GoLang environment. 

**What you expected to happen**:
Syft runs the same locally as in a docker container.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a docker container using the `golang:1.16-alphine.13` (we also tested using Debian images and found the same issues.
2. Install syft within dockerfile, using ```
ARG SYFT_VERSION="v0.30.1"
RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/${SYFT_VERSION}/install.sh | sh -s -- -b /usr/local/bin```
3. Run GotestSum in image, with unit tests which call the syft binary, where we execute the command looks like this: ```args := []string{
		searchLocation,
		"--scope", "all-layers",
		"-o", string(outputFormat),
		"--file", outputFilePath,
	}

	cmd := ExecCommand("syft", args...)```
4. Receive Error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7b2f8b]
 
goroutine 180 [running]:
github.com/anchore/syft/syft/pkg.(*Catalog).Enumerate.func1(0xc0000f8ae0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/github.com/anchore/syft@v0.30.1/syft/pkg/catalog.go:134 +0x6b
created by github.com/anchore/syft/syft/pkg.(*Catalog).Enumerate
/go/pkg/mod/github.com/anchore/syft@v0.30.1/syft/pkg/catalog.go:132 +0x85
```

**Anything else we need to know?**:
Will update this if I think of anything else.

**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar): golang:1.16-alpine3.13 docker image

**Comment by spiffcs** [comment]
Hey @rosswilhite-wk!

Thanks for submitting the issue. 

I noticed `golang:1.16-alphine.13` <= is that a typo?

I built a docker file doing the following:
```
FROM golang:1.16-alpine3.13
RUN go install github.com/anchore/syft@latest
```

This was a bit slower, but when I tried to use the `RUN` line provided syft would not be located in `/usr/local/bin`.

I did a `docker run -it` into the image I built: `docker run -it 638:latest /bin/sh`

From there I ran `syft --scope all-layers -o json --file test.json dir:.`

An sbom was generated for the above command so I was unsuccessful in reproducing the panic.

Would you be able to add `verbose` logging to your output so we could see the previous logs that might have lead to this output?

You can view this output with the `-vvv` flag which will print debug messages

**Comment by rosswilhite-wk** [comment]
We were able to get the unit tests to work using `go install github.com/anchore/syft@v0.30.1`

However, the `curl` installation had to be used when we installed syft on our release image based on `amazonlinux2`. Not sure what the difference is. I can close this if it's not a problem, unless someone else would like to investigate further.

**Comment by spiffcs** [comment]
Awesome to hear it worked. I'll dig in a bit more tonight and see if I can simulate your env with curl and scan our testbed of images.

**Comment by westonsteimel** [comment]
I ran into a similar error when using `grype` in a Docker container.  It seems to happen when there is no `/tmp` directory in the image, which I think makes since based on the comments in the [grype dockerfile](https://github.com/anchore/grype/blob/main/Dockerfile).  Not sure if that would be related to this issue or not, but perhaps it helps.  Below is the dockerfile and error, and uncommenting the `#WORKDIR /tmp` resolves the issue in that instance.

```dockerfile
FROM anchore/syft:v0.30.1 as syft
FROM anchore/grype:0.25.1 as grype
FROM alpine:latest as alpine

RUN apk update && apk add --no-cache \
    ca-certificates

FROM scratch

#WORKDIR /tmp

COPY --from=alpine /etc/ssl/certs /etc/ssl/certs
COPY --from=syft /syft /usr/local/bin/syft
COPY --from=grype /grype /usr/local/bin/grype
```

```
docker run --rm -it syft-test /usr/local/bin/grype -vvv dir:/
```

```
[0000] DEBUG No Refs found from path: /etc/os-release from-lib=syft
[0000] DEBUG No Refs found from path: /usr/lib/os-release from-lib=syft
[0000] DEBUG No Refs found from path: /bin/busybox from-lib=syft
[0000] DEBUG No Refs found from path: /etc/system-release-cpe from-lib=syft
[0000] DEBUG No Refs found from path: /etc/redhat-release from-lib=syft
[0000]  INFO could not identify distro from-lib=syft
[0000]  INFO cataloging directory from-lib=syft
[0000] DEBUG package cataloger "ruby-gemfile-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "python-index-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "python-package-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "php-index-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "javascript-lock-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "dpkgdb-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "rpmdb-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "java-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "apkdb-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "go-module-binary-cataloger" discovered 171 packages from-lib=syft
[0000] DEBUG package cataloger "go-mod-file-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "rust-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG searching for vulnerability matches for pkg=Pkg(type=go-module, name=cloud.google.com/go, version=v0.57.0)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xda6f89]
goroutine 67 [running]:
github.com/anchore/grype/grype/matcher/common.FindMatchesByPackageLanguage(0x0, 0x0, 0x10e5f80, 0x2, 0xc0163c2870, 0x14, 0xc0163bf8b4, 0x13, 0xc0163bf8c8, 0x7, ...)
        /Users/runner/work/grype/grype/grype/matcher/common/language_matchers.go:19 +0x1e9
github.com/anchore/grype/grype/matcher/stock.(*Matcher).Match(0x1970738, 0x0, 0x0, 0x0, 0xc0163c2870, 0x14, 0xc0163bf8b4, 0x13, 0xc0163bf8c8, 0x7, ...)
        /Users/runner/work/grype/grype/grype/matcher/stock/matcher.go:27 +0x345
github.com/anchore/grype/grype/matcher.(*controller).findMatches(0x193ab98, 0x0, 0x0, 0x0, 0xc0240f2000, 0xab, 0xab, 0xc0001bb720)
        /Users/runner/work/grype/grype/grype/matcher/controller.go:97 +0x3b5
github.com/anchore/grype/grype/matcher.FindMatches(...)
        /Users/runner/work/grype/grype/grype/matcher/controller.go:115
github.com/anchore/grype/grype.FindVulnerabilitiesForPackage(...)
        /Users/runner/work/grype/grype/grype/lib.go:28
github.com/anchore/grype/cmd.startWorker.func1(0xc00072c540, 0x7ffc0aabcf77, 0x1, 0x0)
        /Users/runner/work/grype/grype/cmd/root.go:269 +0x468
created by github.com/anchore/grype/cmd.startWorker
        /Users/runner/work/grype/grype/cmd/root.go:204 +0x76
```

**Comment by westonsteimel** [comment]
I wonder if it's fixed by or a case of something similar to https://github.com/anchore/syft/pull/658.

**Comment by westonsteimel** [comment]
Ah, so yes it seems like #658 (or possibly some other similar change in grype itself) has cleared up the panic in my case.  I now get the following when running in a docker container with no `/tmp` dir, which makes perfect sense:

```
[0000] DEBUG checking for available database updates
[0000]  WARN unable to check for vulnerability database update
[0000] DEBUG check for vulnerability update failed: unable to create listing temp file: open /tmp/grype-db-listing425036657: no such file or directory
...
[0000] DEBUG package cataloger "ruby-gemfile-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "python-index-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "python-package-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "php-composer-lock-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "javascript-lock-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "dpkgdb-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "rpmdb-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "java-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "apkdb-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "go-module-binary-cataloger" discovered 194 packages from-lib=syft
[0000] DEBUG package cataloger "go-mod-file-cataloger" discovered 0 packages from-lib=syft
[0000] DEBUG package cataloger "rust-cataloger" discovered 0 packages from-lib=syft
1 error occurred:
	* failed to load vulnerability db: vulnerability database is corrupt (run db update to correct): database metadata not found: /.cache/grype/db/3
```

**Comment by luhring** [comment]
Thanks @westonsteimel!

@rosswilhite-wk Hi! 👋  Do you think this can be closed now?
