### ISSUE TITLE
Result upload to anchore engine failing with "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by robert-heinzmann-logmein** [anchore/syft#817]
**What happened**:

* Configured syft for anchore-engine upload
* Scanned image
* Scan result upload failed

**What you expected to happen**:

* Scan results uploaded to anchore engine

**How to reproduce it (as minimally and precisely as possible)**:

* configure anchore-engine upload
* run `syft docker.io/library/centos:8`

Error is

```
[0024]  INFO uploading results to https://anchore.apps.xxxxxxxx:444/v1/
[0024] DEBUG importing package SBOM
[0025] DEBUG importing image manifest
[0025] DEBUG importing image config
1 error occurred:
        * failed to upload results to host=https://anchore.apps.xxxxxxxxx:444/v1/: unable to complete import session="f8435882877c422dbd8dxxxxxxxxxxxxxx": 500 INTERNAL SERVER ERROR: {
  "detail": {
    "error_codes": []
  },
  "httpcode": 500,
  "message": "failed post url=http://anchore-demo-anchore-engine-catalog:8082/v1/images"
}
```

Catalog Pod log shows

```
"100.96.1.1" - - [12/Feb/2022:21:41:33 +0000] "GET /health HTTP/1.1" 200 5 "-" "kube-probe/1.22"
"100.96.1.1" - - [12/Feb/2022:21:41:53 +0000] "GET /health HTTP/1.1" 200 5 "-" "kube-probe/1.22"
"100.96.1.7" - - [12/Feb/2022:21:41:59 +0000] "POST /v1/imports/images HTTP/1.1" 200 263 "-" "python-requests/2.26.0"
"100.96.1.7" - - [12/Feb/2022:21:42:00 +0000] "POST /v1/imports/images/be3843c4d6ef4d40acc312718b9c8112/packages HTTP/1.1" 200 123 "-" "python-requests/2.26.0"
"100.96.1.7" - - [12/Feb/2022:21:42:00 +0000] "POST /v1/imports/images/be3843c4d6ef4d40acc312718b9c8112/manifest HTTP/1.1" 200 123 "-" "python-requests/2.26.0"
"100.96.1.7" - - [12/Feb/2022:21:42:01 +0000] "POST /v1/imports/images/be3843c4d6ef4d40acc312718b9c8112/image_config HTTP/1.1" 200 123 "-" "python-requests/2.26.0"
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/anchore_engine/services/catalog/api/controllers/default_controller.py", line 192, in add_image
return_object = anchore_engine.services.catalog.importer.import_image(
File "/usr/local/lib/python3.8/site-packages/anchore_engine/services/catalog/importer.py", line 301, in import_image
for t in import_manifest.tags:
TypeError: 'NoneType' object is not iterable
```

Issue seems to be that no tags are sent as part of the manifest

```
[0001] DEBUG image metadata: digest=sha256:d1dc36cf8d9ee8092bb3ea41ddcaeb81f7d60ec58bd867f3d3260a6159326cb5 mediaType=application/vnd.docker.distribution.manifest.v2+json tags=[] from-lib=stereoscope
```

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:

```
[0000]  INFO syft version: 0.37.10
[0000] DEBUG   ├── buildDate: 2022-02-08T00:03:55Z
[0000] DEBUG   ├── compiler: gc
[0000] DEBUG   ├── gitCommit: 0ed284212305c76d65687aad6eaabf91142e0ddc
[0000] DEBUG   ├── gitDescription: v0.37.10
[0000] DEBUG   ├── goVersion: go1.16.13
[0000] DEBUG   ├── platform: linux/amd64
[0000] DEBUG   └── version: 0.37.10
```
- OS (e.g: `cat /etc/os-release` or similar):

```
shell$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
```

**Comment by robert-heinzmann-logmein** [comment]
Just a note, it seems the tags are properly added for the "docker / podman" image sources, as they set the tags explicitly.

https://github.com/anchore/stereoscope/blob/403dd709a3fbe75143340f402cbdc27fba5d01af/pkg/image/docker/tarball_provider.go#L90-L92

```
ubuntu@xxxxx:~$ syft podman:docker.io/library/alpine:latest
...
[0000] DEBUG image metadata: digest=sha256:c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18 mediaType=application/vnd.docker.distribution.manifest.v2+json tags=[docker.io/library/alpine:latest] from-lib=stereoscope
...
[0001]  INFO uploading results to https://anchore.apps.xxxxxxxxx:444/v1/
[0001] DEBUG importing package SBOM
[0001] DEBUG importing image manifest
[0001] DEBUG importing image config
NAME                    VERSION      TYPE
alpine-baselayout       3.2.0-r18    apk
alpine-keys             2.4-r1       apk
apk-tools               2.12.7-r3    apk
busybox                 1.34.1-r3    apk
ca-certificates-bundle  20191127-r7  apk
libc-utils              0.7.2-r3     apk
libcrypto1.1            1.1.1l-r7    apk
libretls                3.3.4-r2     apk
libssl1.1               1.1.1l-r7    apk
musl                    1.2.2-r7     apk
musl-utils              1.2.2-r7     apk
scanelf                 1.3.3-r0     apk
ssl_client              1.34.1-r3    apk
zlib                    1.2.11-r3    apk
```

**Comment by tgerla** [comment]
Hi @robert-heinzmann-logmein, sorry for the long delay replying to this issue. Can you confirm that this is still a problem for you on the latest version of Syft? If it is, we will be happy to dig in and solve it. Thank you!

**Comment by pganeshar** [comment]
Hi @tgerla,
I have exactly the same error.  I build two images using podman: amd and arm.  I then create a manifest using podman and add both images to it.  I then submit the manifest to Anchore engine and it fails to scan.  When I see the event log it says:
```
details:
  msg: 'failed to download, unpack, analyze, and generate image export (9999999999999.dkr.ecr.us-west-2.amazonaws.com/sandbox-example/goserviceeks@sha256:8fd0f9348422863384385ec23b500ac091a9577c78cf87f412ab4ff1ad3fce9f)
    - exception: ''NoneType'' object is not iterable'
level: error
message: Failed to analyze image
```
Can you help please?

**Comment by tgerla** [comment]
Sorry all, we are no longer able to support anchore-engine, and the Syft feature is intended to upload to anchore-enterprise, not anchore-engine. I'm going to close this issue but if you have any further trouble with Syft please open a new ticket or join our Slack and we will be happy to help. Thanks!
